# Generated by Django 4.0.3 on 2022-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kilometer',
            field=models.CharField(max_length=32),
        ),
    ]
