# Generated by Django 4.0.3 on 2022-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_kilometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kilometer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=32),
        ),
    ]
