# Generated by Django 4.0.3 on 2022-04-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_kilometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.CharField(max_length=1024),
        ),
    ]
