# Generated by Django 4.0.3 on 2022-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=128)),
                ('changes', models.CharField(max_length=128)),
            ],
        ),
    ]
